name: samapp
description: A copy of Sam Android App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0-8.2.beta <3.0.0"

# The following section is for library.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  logger: ^0.9.1  #for logging purpose

  transparent_image: ^1.0.0

  bubble: ^1.1.9+1

  json_annotation: ^3.0.0

  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  rxdart: ^0.24.1

  intl: ^0.16.1

  dio: 3.0.9 #latest version
  pretty_dio_logger: ^1.1.1

  fluttertoast: ^4.0.0

  cupertino_icons: ^0.1.3

  flutter_secure_storage: ^3.3.3

  auto_size_text: ^2.1.0

  sembast: ^2.4.4+3

  path_provider: ^1.6.10

  percent_indicator: ^2.1.5


  firebase_core: ^0.4.0+9

  firebase_database: ^3.1.6

  cloud_firestore: ^0.12.9+5

  firebase_messaging: ^6.0.16

  flutter_local_notifications: ^1.4.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  gen_lang: 0.1.3
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Helveticaneue
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
        - asset: assets/fonts/helveticaneuebold.ttf
          weight: 700
        - asset: assets/fonts/helveticaneueitalic.ttf
          style: italic
        - asset: assets/fonts/helveticaneuemedium.ttf
          weight: 500
